repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-yaml
  - id: check-toml
  - id: check-ast
  - id: debug-statements
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: fix-byte-order-marker
  - id: mixed-line-ending
  - id: detect-private-key
- repo: https://github.com/psf/black
  rev: 21.4b2
  hooks:
  - id: black
